<?php

use mp_general\base\SSV_Global;

if (!defined('ABSPATH')) {
    exit;
}

function ssv_add_ssv_file_manager_options()
{
    SSV_Global::addMenuItem('File Manager Options', 'File Manager', 'ssv-file-manager-settings', 'ssv_file_manager_options_page_content');
}

function wpse_141088_upload_dir($dir)
{
    $currentFolder = '/mycustomdir';
    return [
               'path'   => $dir['basedir'] . $currentFolder,
               'url'    => $dir['baseurl'] . $currentFolder,
               'subdir' => $currentFolder,
           ] + $dir;
}

function ssv_file_manager_options_page_content()
{
    if (isset($_FILES['file'])) {
        $uploadedfile     = $_FILES['file'];
        $upload_overrides = ['test_form' => false];
        // Register our path override.
        add_filter('upload_dir', 'wpse_141088_upload_dir');
        $movefile = wp_handle_upload($uploadedfile, $upload_overrides);
        if (function_exists('dos_file_upload')) {
            call_user_func('dos_file_upload', $movefile['file']);
            wp_delete_file($movefile['file']);
        }
        remove_filter('upload_dir', 'wpse_141088_upload_dir');
        if ( $movefile && ! isset( $movefile['error'] ) ) {
            echo "File is valid, and was successfully uploaded.\n";
            var_dump( $movefile );
        } else {
            /**
             * Error generated by _wp_handle_upload()
             * @see _wp_handle_upload() in wp-admin/includes/file.php
             */
            echo $movefile['error'];
        }
    }
    $activeTab = $_GET['tab'] ?? 'general';
    ?>
    <form method="post" enctype="multipart/form-data">
        <input type="file" name="file">
        <button type="submit">Submit</button>
    </form>
    <?php
    return;
    ?>
    <div class="wrap">
        <h1>File Manager Options</h1>
        <h2 class="nav-tab-wrapper">
            <a href="?page=<?= esc_html($_GET['page']) ?>&tab=general" class="nav-tab <?= $activeTab === 'general' ? 'nav-tab-active' : '' ?>">General</a>
            <a href="http://bosso.nl/plugins/ssv-file-manager/" target="_blank" class="nav-tab">
                Help <!--suppress HtmlUnknownTarget -->
                <img src="<?= esc_url(SSV_Global::URL) ?>/images/link-new-tab-small.png" width="14" style="vertical-align:middle">
            </a>
        </h2>
        <?php
        /** @noinspection PhpIncludeInspection */
        require_once $activeTab . '.php';
        ?>
    </div>
    <?php
}

add_action('admin_menu', 'ssv_add_ssv_file_manager_options');

function ssv_add_ssv_file_manager_super_admin_options()
{
    add_submenu_page('ssv_settings', 'File Manager Options', 'File Manager', 'manage_options', 'ssv-file-manager-settings', 'ssv_file_manager_super_admin_options_page_content');
}

function ssv_file_manager_super_admin_options_page_content()
{
    $activeTab = $_GET['tab'] ?? 'general';
    ?>
    <div class="wrap">
        <h1>File Manager Options</h1>
        <h2 class="nav-tab-wrapper">
            <a href="?page=<?= esc_html($_GET['page']) ?>&tab=general" class="nav-tab <?= $activeTab === 'general' ? 'nav-tab-active' : '' ?>">General</a>
            <a href="http://bosso.nl/plugins/ssv-file-manager/" target="_blank" class="nav-tab">
                Help <!--suppress HtmlUnknownTarget -->
                <img src="<?= esc_url(SSV_Global::URL) ?>/images/link-new-tab-small.png" width="14" style="vertical-align:middle">
            </a>
        </h2>
        <?php
        /** @noinspection PhpIncludeInspection */
        require_once 'network-admin' . DIRECTORY_SEPARATOR . $activeTab . '.php';
        ?>
    </div>
    <?php
}

add_action('network_admin_menu', 'ssv_add_ssv_file_manager_super_admin_options', 9);
